# ----------------------- #
#      Main Configs       #
# ----------------------- #
#http://localhost:8080 

url: http://david.podhola.net
gitlocation: https://github.com/davidpodhola/davidpodhola.github.io.git
gitbranch: master
title: David Podhola - F# developer with sales and marketing skills
description: >
    I love to code and develop application. Have been doing it in BASIC and Pascal since 1986 for fun, professionally since 1994.

source: source/
blog: source/blog/
blogIndex: source/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: output/
deploy: deploy
themes: themes
